from __future__ import annotations
from pathlib import Path

MARKER='SM-PH-EMERGENCY-RETURN-RECOVERY-20260916-CURRENT'


def _replace_once(path:Path,old:str,new:str):
    s=path.read_text(encoding='utf-8'); n=s.count(old)
    if n!=1: raise SystemExit(f'EMERGENCY_RECOVERY_PATCH_ANCHOR_MISMATCH path={path} count={n}')
    path.write_text(s.replace(old,new,1),encoding='utf-8')


def apply_emergency_return_recovery(root:Path)->None:
    bridge=root/'scoremax_ph_bridge_v6611d.py'
    prod=root/'scoremax_production.py'

    s=bridge.read_text(encoding='utf-8')
    if 'def reconcile_governed_emergency_rejections' not in s:
        s += '''\n\ndef reconcile_governed_emergency_rejections(c):\n    \"\"\"Queue exactly one PH incident for a governed pre-bridge Emergency Direct rejection.\"\"\"\n    review_table=c.execute(\"SELECT 1 FROM sqlite_master WHERE type='table' AND name='question_review_events'\").fetchone()\n    incident_table=c.execute(\"SELECT 1 FROM sqlite_master WHERE type='table' AND name='ph_bridge_incident_events_v6611d'\").fetchone()\n    if not review_table or not incident_table:\n        return 0\n    rows=c.execute(\"\"\"SELECT q.* FROM questions q JOIN content_import_batches b ON b.id=q.source_import_batch_id\n                       WHERE b.intake_mode='EMERGENCY_DIRECT' AND b.source_system='POWER_HOUSE_GOVERNED'\n                         AND q.status='Rejected' AND q.review_status='Rejected' AND COALESCE(q.active,0)=0 ORDER BY q.id\"\"\").fetchall()\n    queued=0\n    for q in rows:\n        ev=c.execute(\"SELECT * FROM question_review_events WHERE question_id=? AND action='Rejected' ORDER BY id DESC LIMIT 1\",(q['id'],)).fetchone()\n        if not ev: continue\n        existing=c.execute(\"SELECT 1 FROM ph_bridge_incident_events_v6611d WHERE question_db_id=? AND feedback_code LIKE 'SMAR-%' LIMIT 1\",(q['id'],)).fetchone()\n        if existing: continue\n        code=f\"SMAR-RECOVER-{int(q['id'])}-{int(ev['id'])}\"\n        context={'source':'SCOREMAX_ADMIN_REVIEW_RECOVERY','reason_code':str(ev['reason_code'] or ''),'question_db_id':int(q['id']),'question_id':str(q['question_id'] or ''),'subject':str(q['subject'] or ''),'chapter':str(q['chapter'] or ''),'requested_action':'POWER_HOUSE_EXCEPTION','withdrawal_authority':'POWER_HOUSE','page':f\"/admin/questions/{int(q['id'])}\"}\n        msg=queue_reported_question_incident(c,q,code,str(ev['reason_code'] or 'ADMIN_REJECT'),'HIGH',str(ev['note'] or ev['reason_code'] or 'ScoreMax admin rejected learner-facing question.'),context)\n        if not msg: raise RuntimeError(f'EMERGENCY_REJECTION_RECONCILIATION_IDENTITY_FAILED question_db_id={int(q[\"id\"])}')\n        queued+=1\n    if queued: c.commit()\n    return queued\n\n# SM-PH-EMERGENCY-RETURN-RECOVERY-20260916-CURRENT\n'''
        bridge.write_text(s,encoding='utf-8')

    old="install_admin_view_as(scoremax.app)\napplication=scoremax.app"
    new="""install_admin_view_as(scoremax.app)\nimport os as _emergency_return_os\nimport json as _emergency_return_json\nimport scoremax_ph_bridge_v6611d as _emergency_return_bridge\nimport scoremax_integration_v1 as _emergency_return_integration\n_emergency_return_conn=scoremax.db()\n_emergency_return_dispatch={}\n_emergency_return_incident_health={}\ntry:\n    _emergency_return_queued=_emergency_return_bridge.reconcile_governed_emergency_rejections(_emergency_return_conn)\n    # Always retry any durable due PH outbox work. This covers an incident queued by an earlier\n    # release when the incident dispatch route was not yet configured, without creating a new event.\n    _emergency_return_dispatch=_emergency_return_integration.dispatch_due(_emergency_return_conn,limit=20,timeout=8)\n    _emergency_return_health=_emergency_return_integration.integration_health(_emergency_return_conn)\n    for _lane in _emergency_return_health.get('directions') or []:\n        if _lane.get('contract')=='SM_PH_CONTENT_INCIDENT_V1':\n            _emergency_return_incident_health={k:_lane.get(k) for k in (\n                'connection_state','queued_count','retrying_count','in_flight_count','dead_letter_count',\n                'quarantined_count','last_error_code','last_error_at','last_success_at','last_dispatched_at','oldest_backlog_at'\n            )}\n            break\nfinally:\n    _emergency_return_conn.close()\n# Observability is deliberately presence/status-only. Never log endpoint values, credentials, payloads or receipts.\n_emergency_return_config={\n    'base_url_configured':bool(_emergency_return_os.environ.get('SCOREMAX_POWER_HOUSE_BASE_URL')),\n    'token_configured':bool(_emergency_return_os.environ.get('SCOREMAX_TO_POWER_HOUSE_TOKEN')),\n    'hmac_configured':bool(_emergency_return_os.environ.get('SCOREMAX_TO_POWER_HOUSE_HMAC_SECRET')),\n}\nprint('SCOREMAX_EMERGENCY_RETURN_RECOVERY queued='+str(_emergency_return_queued)+' dispatch='+_emergency_return_json.dumps(_emergency_return_dispatch,sort_keys=True,separators=(',',':'))+' config='+_emergency_return_json.dumps(_emergency_return_config,sort_keys=True,separators=(',',':'))+' incident_health='+_emergency_return_json.dumps(_emergency_return_incident_health,sort_keys=True,separators=(',',':')),flush=True)\napplication=scoremax.app"""
    _replace_once(prod,old,new)

    print(f'{MARKER} PASS startup_reconciliation=true durable_outbox_retry=true dispatch_count_contract=true safe_presence_observability=true durable_incident_health=true prebridge_only=true duplicate_admin_incident_blocked=true persistent_guard_v4_reused=true second_exception_system=false',flush=True)
